id: A92A7799E
title: 'Jewels of Many Colours: Ordinary Fire Pūjas for the Four Activities Based
  on a Single Substance to Easily Conclude Approach and Accomplishment'
type: translation
pechas:
- I00C8982D
- IF816BFE3
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:00:52.393893
  last_modified_at: 2023-01-04 12:00:52.393914
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I00C8982D/1A04: 31EC
  IF816BFE3/F2D4: 31EC
